config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  scope "/:locale" do
    get "sessions/new"

    get "home/index"

    get "styleguide", to: "styles#atoms"
    get "styles/atoms"
    get "styles/molecules"
    get "styles/organisms"

    get "account/ideas"

    resources :users, only: %i[new create edit update] do
      resources :goals, only: %i[create destroy]
    end

    resources :ideas do
      resources :comments
      resources :photos, only: %i[index create]
    end

    resources :sessions, only: %i[new create destroy]

    get "login", to: "sessions#new"
    get "signup", to: "users#new"

    get "account", to: "account#edit"
    patch "account", to: "account#update"
    get "account/goals"
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
  belongs_to :user
  
  validates :user, presence: true
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 75 }

  has_many :comments
  belongs_to :user

  has_and_belongs_to_many :users
  paginates_per 9

  scope :search, ->(term) { title_contains(term).or(description_contains(term)) }

  scope :most_recent, -> { all.order(created_at: :desc).limit(3) }

  scope :title_contains, ->(term) { where('title LIKE ?', "%#{term}%") }
  scope :description_contains, ->(term) { where('description LIKE ?', "%#{term}%") }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :ideas
  before_validation :downcase_email
  validates :email, uniqueness: true
  validates :email, :password, presence: true
  validates :role, inclusion: { in: %w[registered admin] }
  # attribute :role, :string, default: 'registered'

  after_initialize :default_role!
  has_secure_password

  has_and_belongs_to_many :goals, class_name: 'Idea'

  mount_uploader :avatar, AvatarUploader

  private

  def downcase_email
    self.email = email.downcase
  end

  def default_role!
    self.role ||= 'registered'
  end
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  before_action :ensure_authenticated

  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to account_path
    else
      render 'edit'
    end
  end

  def ideas
    @ideas = current_user.ideas
  end

  def goals
    @goals = current_user.goals
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :avatar, :password)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :ensure_authenticated, only: %i[create destroy]

  def create
    @idea = Idea.find(params[:idea_id])
    current_user.goals << @idea

    respond_to do |format|
      format.html { redirect_to idea_path(@idea) }
      format.js { render 'create' }
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @idea = Idea.find(params[:id])
    @user.goals.delete(@idea)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ideas = Idea.most_recent
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  include RolesHelper
  before_action :ensure_authenticated,     only: %i[new create edit update destroy]
  before_action :load_idea,                only: %i[show edit update destroy]
  before_action :authorize_to_edit_idea,   only: %i[edit update destroy]

  def index
    @search_term = params[:q]
    @ideas = Idea.search(@search_term).page(params[:page])
  end

  def show
    @comment = Comment.new
    @display_add_comment = logged_in?
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_resource_params)
    @idea.user = current_user
    if @idea.save
      redirect_to(ideas_path)
    else
      render "new"
    end
  end

  def edit; end

  def update
    if @idea.update(idea_resource_params)
      redirect_to account_ideas_path
    else
      render "edit"
    end
  end

  def destroy
    @idea.destroy!
    redirect_to account_ideas_path
  end

  private

  def idea_params
    params.permit(:title, :description, :photo_url)
  end

  def idea_resource_params
    params.require(:idea).permit(:title, :photo_url, :done_count, :description)
  end

  def authorize_to_edit_idea
    redirect_to account_path unless can_edit? @idea
  end

  def load_idea
    @idea = Idea.find(params[:id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  include RolesHelper
  before_action :ensure_authenticated
  before_action :load_idea
  before_action :authorize

  def index
    @query = params[:query]
    @query ||= @idea.title
    @photos = Unsplash::Photo.random(query: @query, count: 3)
  end

  def create
    @idea.update_attributes photo_url: params[:photo_url]
    redirect_to edit_idea_path(@idea)
  end

  private

  def load_idea
    @idea = Idea.find(params[:idea_id])
  end

  def authorize
    redirect_to account_path unless can_edit? @idea
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  def atoms
  end

  def molecules
  end

  def organisms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_admin, only: %i[edit update]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to ideas_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update(edit_user_params)
      redirect_to account_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def edit_user_params
    params.require(:user).permit(:email, :name, :role)
  end

  def ensure_admin
    redirect_to account_path unless current_user.role == 'admin'
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
  def has_goal?(goal)
    return false unless logged_in?

    # this resulted in n+1 problem
    # current_user.goals.include? goal
    #
    # this did not correct the n+1 problem, still created lots of requests
    # @goals ||= current_user.goals
    # @goals.include? goal
    #
    # this didn't work, resulted in undefinded method: includes
    # @user ||= User.find(session[:user_id]).includes(:goals)

    @goal_user ||= User.select(:id, :role).includes(:goals).select(:id).find(session[:user_id])
    @goal_user.goals.include? goal
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
  def can_edit?(idea)
    case current_user.role
    when 'admin' then true
    when 'registered' then current_user == idea.user
    else false
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/create.js.erb
var svgUse = document.createElementNS("http://www.w3.org/2000/svg", 'use');
svgUse.setAttribute('href', '<%= image_path("icons-defs.svg") %>#delete');

var svgDelete = document.createElementNS("http://www.w3.org/2000/svg", "svg");
svgDelete.setAttribute('class', 'icon-delete');
svgDelete.setAttribute('role', 'presentation');
svgDelete.appendChild(svgUse);

var buttonText = document.createTextNode('Remove Goal');
var removeGoalLink = document.createElement('a');
removeGoalLink.className = 'btn delta';
removeGoalLink.appendChild(svgDelete);
removeGoalLink.appendChild(buttonText);
removeGoalLink.setAttribute('id', 'goal-<%= @idea.id  %>')
removeGoalLink.setAttribute('data-remote','true')
removeGoalLink.setAttribute('data-method','delete')
removeGoalLink.setAttribute('rel', 'nofollow')
removeGoalLink.setAttribute('href', '<%= user_goal_path(current_user, @idea)  %>')


var addGoalLink = document.getElementById('goal-<%= @idea.id %>');
addGoalLink.parentNode.replaceChild(removeGoalLink, addGoalLink);

app/views/goals/destroy.js.erb
const idea = document.getElementById('goal-<%= @idea.id  %>')
const container = idea.parentElement
console.log(idea)
console.log(idea.parentElement)
idea.parentElement.removeChild(idea)

const form = document.createElement('form')

const button = document.createElement('button')
button.innerText = "Add Goal"

form.appendChild(button)
container.appendChild(form)

app/views/home/index.html.erb
<main>
  <div class="masthead">
    <div class="content-wrapper">
      <h1>Get inspired. Create your bucket list. Share.</h1>

      <%= form_tag(ideas_path, method: :get) do  %>
        <div class="input-inline">
          <label class="input-group__label" for="banner-search-input">Inspire me</label>
          <div class="input-row">
            <input id="banner-search-input" class="input-row__field" type="text" name="search" placeholder="e.g. Swimming with dolphins">
            <button class="btn btn--inline" type="submit">Search</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="content-wrapper">
    <h2>Some ideas</h2>
    <ul class="bare-list float-grid css-grid">
      <% @ideas.each do |idea|  %>
        <%= render(partial: "idea_card", locals: {idea: idea})  %>
      <% end %>
    </ul>
  </div>
  <div class="see-more">
    <%= form_tag(ideas_path,  method: :get,  class: 'form') do  %>
      <%= button_tag("See more", class: 'btn')  %>
    <% end %>
  </div>
</main>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/index.html.erb
<div class="content-wrapper">
  <nav>
    <ul class="sub-navigation">
      <%= link_to('Idea', edit_idea_path(@idea))  %>
      <li><a href="#nolink">Photos</a></li>
    </ul>
  </nav>
  <h1>Suggested</h1>
  <div class="content-wraper">
    <%= form_tag(idea_photos_path(@idea), method: :get, class: 'form--inpage') do %>
      <div class="input-inline">
        <label class="input-group__label" for="query">Change the search term</label>
        <div class="input-row">
          <%= text_field_tag(:query, @query, class: 'input_row__field')  %>
          <button class="btn btn--primary btn--inline" type="submit">Go</button>
        </div>
      </div>
    <% end %>
    <ul class="bare-list float-grid css-grid">
      <% @photos.each do |photo|  %>
        <li>
          <div class="card">
            <div class="card__thumb">
              <%= image_tag(photo.urls.regular)  %>
            </div>
          </div>
          <%= form_tag(idea_photos_path(@idea) ) do  %>
            <div class="prompt">
              <%= hidden_field_tag(:photo_url, photo.urls.regular)  %>
              <%= submit_tag('Use this photo', class: 'btn btn--primary prompt__confirm')  %>
            </div>
          <% end %>
          <p>Photo taken by <%= photo.user.name  %>, available at <%= link_to 'unsplash.com', photo.links.html  %> </p>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/styles/_button.html.erb
<button class="btn" type="button"> <%= label %> </button>

app/views/styles/_link_button.html.erb
<a class="btn" href="#nolink"><%= label    %></a> 

app/views/styles/_nav.html.erb
<div>
<% if(current == true) %>
  <%= link_to(title, uri, class: 'current') %>
<% else %>
  <%= link_to(title, uri) %> 
<% end %>
</div>

app/views/styles/_navigation.html.erb
<nav>
  <ul class="sub-navigation">
    <li><%= link_to "Atoms", styleguide_path  %></li>
    <li><%= link_to "Molecules", styles_molecules_path  %></li>
    <li><%= link_to "Organisms", styles_organisms_path  %></li>
    <li><a href="templates.html">Templates</a></li>
    <li><a href="#pages">Pages</a></li>
  </ul>
</nav>

app/views/styles/_primary_button.html.erb
<button class="btn btn--primary" type="button"><%= label %></button>

app/views/styles/_prompt.html.erb
<div class="prompt">
          <a class="prompt__cancel" href="#cancel">Cancel</a>
          <button class="btn btn--primary prompt__confirm" type="submit"><%= label %></button>
        </div>

app/views/styles/_warning_button.html.erb
<button class="btn btn--warning" type="button"><%= label %></button>

app/views/styles/atoms.html.erb
<main class="content-wrapper">
      <div>
        <h1>Style Guide</h1>
        <p>
          Our Style Guide is based upon the principles of Atomic design, a methodology composed of five distinct stages working together to create interface design systems in a more deliberate and hierarchical manner.
        </p>
        <%= render(partial: "navigation")  %>
        <h2>Atoms</h2>
        <p>
          Atoms are the basic building blocks of matter. Applied to web interfaces, atoms are our HTML tags, such as a form label, an input or a button.
        </p>
        <p>
          Atoms can also include more abstract elements like color palettes, fonts and even more invisible aspects of an interface like animations.
        </p>
        <p>
          Like atoms in nature they’re fairly abstract and often not terribly useful on their own. However, they’re good as a reference in the context of a pattern library as you can see all your global styles laid out at a glance.
        </p>
        <nav>
          <ol class="ordered-navigation">
            <li><a href="#palette">Palette</a></li>
            <li><a href="#typography">Typography</a></li>
            <li><a href="#buttons">Buttons</a></li>
            <li><a href="#forms">Form Elements</a></li>
            <li><a href="#icons">Icons</a></li>
          </ol>
        </nav>
      </div>
      <section class="sg-section" id="palette">
        <h3 class="beta">01. Palette</h3>
        <ul class="sg-palette">
          <li>
            <div data-bgColor="blue"></div>
            <p>#2c9cf2</p>
          </li>
          <li>
            <div data-bgColor="black"></div>
            <p>#192127</p>
          </li>
          <li>
            <div data-bgColor="darkest"></div>
            <p>#72797e</p>
          </li>
          <li>
            <div data-bgColor="dark"></div>
            <p>#afbac4</p>
          </li>
          <li>
            <div data-bgColor="gray"></div>
            <p>#bbc1c6</p>
          </li>
          <li>
            <div data-bgColor="light"></div>
            <p>#e3e5e9</p>
          </li>
          <li>
            <div data-bgColor="lightest"></div>
            <p>#f7f9fc</p>
          </li>
          <li>
            <div data-bgColor="red"></div>
            <p>#e25d43</p>
          </li>
        </ul>
      </section>
      <section class="sg-section" id="typography">
        <h3 class="beta">02. Typography</h3>
        <div class="sg-inlineblock">
          <h4>Glyph</h4>
          <p class="giga">Aa</p>
        </div>
        <div class="sg-inlineblock sg-weights">
          <h4>Weights</h4>
          <ul class="bare-list">
            <li>Regular</li>
            <li><em>Regular Italic</em></li>
            <li><strong>Bold</strong></li>
            <li><strong><em>Bold Italic</em></strong></li>
          </ul>
        </div>
        <table class="table--lines sg-typotable">
          <thead>
            <tr>
              <th>Style</th>
              <th>Desktop</th>
              <th>Tablet</th>
              <th>Mobile</th>
              <th>Line-height</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="alpha">H1 / .alpha</td>
              <td>48px</td>
              <td>40px</td>
              <td>36px</td>
              <td>1.2</td>
            </tr>
            <tr>
              <td class="beta">H2 / .beta</td>
              <td>36px</td>
              <td>32px</td>
              <td>28px</td>
              <td>1.2</td>
            </tr>
            <tr>
              <td class="gamma">H3 / .gamma</td>
              <td>28px</td>
              <td>28px</td>
              <td>24px</td>
              <td>1.2</td>
            </tr>
            <tr>
              <td class="delta">H4 / .delta</td>
              <td>13px</td>
              <td>13px</td>
              <td>13px</td>
              <td>1.5</td>
            </tr>
            <tr>
              <td class="epsilon">H5 / .epsilon</td>
              <td>14px</td>
              <td>14px</td>
              <td>14px</td>
              <td>1.4</td>
            </tr>
            <tr>
              <td class="zeta">H6 / .zeta</td>
              <td>12px</td>
              <td>12px</td>
              <td>12px</td>
              <td>1.4</td>
            </tr>
            <tr>
              <td class="sg-header-button">Action/Button</td>
              <td>13px</td>
              <td>13px</td>
              <td>13px</td>
              <td>1</td>
            </tr>
            <tr>
              <td>Paragraph text</td>
              <td>15px</td>
              <td>15px</td>
              <td>15px</td>
              <td>1.6</td>
            </tr>
          </tbody>
        </table>
      </section>
      <section class="sg-section" id="buttons">
        <h3 class="beta">03. Buttons</h3>
        <h4>Default button</h4>
        <div>
          <button class="btn" type="button">Button</button>
          <a class="btn" href="#nolink">Link Button</a>
        </div>
        <h4>Primary button</h4>
        <div>
          <button class="btn btn--primary" type="button">Primary button</button>
        </div>
        <h4>Negative button</h4>
        <div>
          <button class="btn btn--warning" type="button">Warning button</button>
        </div>
      </section>
      <section class="sg-section" id="forms">
        <h3 class="beta">04. Form Elements</h3>
        <div>
          <h4 class="gamma">Input field</h4>
          <div class="input-group input-group--horizontal">
            <label class="input-group__label" for="sg-input">Input label</label>
            <input id="sg-input" class="input-group__field" type="text" name="sg-input" placeholder="Placeholder text">
          </div>
        </div>
        <div>
          <h4 class="gamma">Text area</h4>
          <div class="input-group input-group--horizontal">
            <label class="input-group__label" for="sg-textarea">Text area label</label>
            <textarea id="sg-textarea" class="input-group__field"></textarea>
          </div>
        </div>
        <div>
          <h4 class="gamma">Validation message on 1 column form</h4>
          <div class="alert">
            Please fill out a valid email address.
            <p>Please enter name.</p>
            <ul>
              <li>Phone number missing.</li>
              <li>Postcode missing.</li>
            </ul>
          </div>
        </div>
        <div>
          <h4 class="gamma">Validation message on 2 column form</h4>
          <div class="alert alert--wide">
            Please fill out a valid email address.
            <p>Please enter name.</p>
            <ul>
              <li>Phone number missing.</li>
              <li>Postcode missing.</li>
            </ul>
          </div>
        </div>
      </section>
      <section class="sg-section" id="icons">
        <h3 class="beta">05. Icons</h3>
        <div>
          <ul>
            <li>
              <svg class="icon-heart" role="presentation">
                <use xlink:href="<%= asset_path('icons-defs.svg#heart')  %>"></use>
              </svg>
            </li>
            <li>
              <svg class="icon-heart icon-heart--liked" role="presentation">
                <use xlink:href="<%= asset_path('icons-defs.svg#heart')  %>"></use>
              </svg>
            </li>
            <li>
              <svg class="icon-pluss" role="presentation">
                <use xlink:href="<%= asset_path('icons-defs.svg#pluss')  %>"></use>
              </svg>
            </li>
            <li>
              <svg class="icon-edit" role="presentation">
                <use xlink:href="<%= asset_path('icons-defs.svg#edit')  %>"></use>
              </svg>
            </li>
            <li>
              <svg class="icon-delete" role="presentation">
                <use xlink:href="<%= asset_path('icons-defs.svg#delete')  %>"></use>
              </svg>
            </li>
            <li>
              <svg class="icon-edit" role="presentation">
                <use xlink:href="<%= asset_path('icons-defs.svg#edit')  %>"></use>
              </svg>
            </li>
          </ul>
        </div>
      </section>
    </main>

app/views/styles/molecules.html.erb
<main class="content-wrapper">
  <div>
    <%= render(partial: "navigation")  %>
    <h1>Molecules</h1>
    <p>
    Things start getting more interesting and tangible when we start combining atoms together. Molecules are groups of atoms bonded together and are the smallest fundamental units of a compound. These molecules take on their own properties and serve as the backbone of our design systems.
    </p>
    <p>
    For example, a form label, input or button isn't too useful by itself, but combine them together as a form and now they can actually do something.
    </p>
    <p>
    Building up to molecules from atoms encourages a “do one thing and do it well” mentality. While molecules can be complex, as a rule of thumb they are relatively simple combinations of atoms built for reuse.
    </p>
    <nav>
      <ol class="ordered-navigation">
        <li><a href="#card">Card</a></li>
        <li><a href="#logo">Logo</a></li>
        <li><a href="#search">Search</a></li>
        <li><a href="#navigation">Navigation</a></li>
        <li><a href="#cancel-confirm">Cancel / Confirm prompt</a></li>
        <li><a href="#like">Like / Liked button</a></li>
      </ol>
    </nav>
  </div>
  <section class="sg-section" id="card">
    <h2>01. Card</h2>
    <div class="card">
      <div class="card__thumb">
        <a href="#">
          <img src="http://fpoimg.com/255x170?text=Preview"
               alt="Northern lights over mountain covered in snow">
        </a>
        <div class="card__intro">
          <h4 class="card__title">See the northern lights</h4>
          <span>1,223 have done this</span>
        </div>
      </div>
      <div class="card__footer">
        <button class="card__btn card__like delta" data-like="see-the-northern-lights">
          <svg class="icon-heart icon-heart--liked" role="presentation">
            <use xlink:href="<%= asset_url("icons-defs.svg" + "#heart") %>"></use>
          </svg>
          Like
        </button>
        <button class="card__btn card__add delta" data-addGoal="see-the-northern-lights">
          <svg class="icon-pluss" role="presentation">
            <use xlink:href="<%= asset_url("icons-defs.svg" + "#pluss") %>"></use>
          </svg>
          Add Goal
        </button>
      </div>
    </div>
  </section>
  <section class="sg-section" id="logo">
    <h2>02. Logo</h2>
    <h3>Default logo</h3>
    <div class="logo">
      <a href="/"><span><i>My</i> Bucket List</span></a>
    </div>
    <h3>Negative logo</h3>
    <p>Used on dark background, like in the site footer.</p>
    <div class="sg-dark-bg">
      <div class="logo logo--inverted footer__logo">
        <a href="/"><span><i>My</i> Bucket List</span></a>
      </div>
    </div>
  </section>
  <section class="sg-section" id="search">
    <h2>03. Search</h2>
    <div class="input-inline">
      <label class="input-group__label" for="global-search-input">Looking for inspiration?</label>
      <div class="input-row">
        <input id="global-search-input" class="input-row__field" type="text" name="global-search" placeholder="e.g. Swimming with dolphins">
        <button class="btn btn--inline" type="submit">Search</button>
      </div>
    </div>
  </section>
  <section class="sg-section" id="navigation">
    <h2>04. Navigation</h2>
    <h3>Primary navigation</h3>
    <nav class="site-header__nav">
      <ul class="main-navigation">
        <li><a href="#nolink">Inspiration</a></li>
        <li><a href="#nolink">Sign Up</a></li>
        <li><a href="#nolink">Log In</a></li>
      </ul>
    </nav>
    <h3>Secondary navigation</h3>
    <nav>
      <ul class="sub-navigation">
        <li><a href="styleguide.html" class="current">Atoms</a></li>
        <li><a href="molecules.html">Molecules</a></li>
        <li><a href="organisms.html">Organisms</a></li>
        <li><a href="#templates">Templates</a></li>
        <li><a href="#pages">Pages</a></li>
      </ul>
    </nav>
    <h3>Footer navigation</h3>
    <div class="sg-dark-bg">
      <nav class="footer__navigation">
        <ul>
          <li><a href="#nolink">About</a></li>
          <li><a href="#nolink">Style Guide</a></li>
          <li><a href="#nolink">Terms of Use</a></li>
        </ul>
      </nav>
    </div>
    <h3>Pagination</h3>
    <div>
      <ul class="pagination">
        <li><a href="#nolink">First</a></li>
        <li><a href="#nolink">Previous</a></li>
        <li>...</li>
        <li><a href="#nolink">5</a></li>
        <li><a href="#nolink" class="current">6</a></li>
        <li><a href="#nolink">7</a></li>
        <li>...</li>
        <li><a href="#nolink">Next</a></li>
        <li><a href="#nolink">Last</a></li>
      </ul>
    </div>
    <h3>Filters</h3>
    <div>
      <ul class="tags-list">
        <li><a href="#tag1" data-filter="tag-1">Tag 1</a></li>
        <li><a href="#tag2" data-filter="tag-2">Tag 2</a></li>
        <li>
          <a href="#tag3" class="selected" data-filter="tag-3">
            Tag 3
            <i class="remove-tag" data-remove-tag="tag-3">&times;</i>
          </a>
        </li>
        <li><a href="#tag4" data-filter="tag-4">Tag 4</a></li>
      </ul>
    </div>
    <h3>See more</h3>
    <div>
      <div class="see-more">
        <button class="btn" type="button" data-more="true">See more</button>
      </div>
    </div>
  </section>
  <section class="sg-section" id="cancel-confirm">
    <h2>05. Cancel or Confirm prompt</h2>
    <div class="prompt">
      <a class="prompt__cancel" href="#cancel">Cancel</a>
      <button class="btn btn--primary prompt__confirm" type="button">Update profile</button>
    </div>
  </section>
  <section class="sg-section" id="like">
    <h2>06. Like or Liked button</h2>
    <div class="card">
      <div class="card__footer">
        <div>
          <button class="card__btn card__like delta" data-like="see-the-northern-lights">
            <svg class="icon-heart" role="presentation">
              <use xlink:href="<%= asset_path('icons-defs.svg#heart')  %>"></use>
            </svg>
            Like
          </button>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card__footer">
        <div>
          <button class="card__btn card__like delta" data-like="see-the-northern-lights">
            <svg class="icon-heart icon-heart--liked" role="presentation">
              <use xlink:href="<%= asset_path('icons-defs.svg#heart')  %>"></use>
            </svg>
            Liked
          </button>
        </div>
      </div>
    </div>
  </section>
</main>