config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  scope "/:locale" do
    get "sessions/new"

    get "home/index"

    get "styleguide", to: "styles#atoms"
    get "styles/atoms"
    get "styles/molecules"
    get "styles/organisms"

    get "account/ideas"

    resources :users, only: %i[new create edit update] do
      resources :goals, only: %i[create destroy]
    end

    resources :ideas do
      resources :comments
      resources :photos, only: %i[index create]
    end

    resources :sessions, only: %i[new create destroy]

    get "login", to: "sessions#new"
    get "signup", to: "users#new"

    get "account", to: "account#edit"
    patch "account", to: "account#update"
    get "account/goals"
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :idea
  belongs_to :user
  
  validates :user, presence: true
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { maximum: 75 }

  has_many :comments
  belongs_to :user

  has_and_belongs_to_many :users
  paginates_per 9

  scope :search, ->(term) { title_contains(term).or(description_contains(term)) }

  scope :most_recent, -> { all.order(created_at: :desc).limit(3) }

  scope :title_contains, ->(term) { where('title LIKE ?', "%#{term}%") }
  scope :description_contains, ->(term) { where('description LIKE ?', "%#{term}%") }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :ideas
  before_validation :downcase_email
  validates :email, uniqueness: true
  validates :email, :password, presence: true
  validates :role, inclusion: { in: %w[registered admin] }
  # attribute :role, :string, default: 'registered'

  after_initialize :default_role!
  has_secure_password

  has_and_belongs_to_many :goals, class_name: 'Idea'

  mount_uploader :avatar, AvatarUploader

  private

  def downcase_email
    self.email = email.downcase
  end

  def default_role!
    self.role ||= 'registered'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  helper_method :logged_in?, :current_user

  def default_url_options
    { locale: I18n.locale }
  end

  def logged_in?
    session[:user_id].present?
  end

  def ensure_authenticated
    redirect_to login_path unless logged_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :ensure_authenticated, only: %i[create destroy]

  def create
    @idea = Idea.find(params[:idea_id])
    current_user.goals << @idea

    respond_to do |format|
      format.html { redirect_to idea_path(@idea) }
      format.js { render 'create' }
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @idea = Idea.find(params[:id])
    @user.goals.delete(@idea)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ideas = Idea.most_recent
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  include RolesHelper
  before_action :ensure_authenticated,     only: %i[new create edit update destroy]
  before_action :load_idea,                only: %i[show edit update destroy]
  before_action :authorize_to_edit_idea,   only: %i[edit update destroy]

  def index
    @search_term = params[:q]
    @ideas = Idea.search(@search_term).page(params[:page])
  end

  def show
    @comment = Comment.new
    @display_add_comment = logged_in?
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(idea_resource_params)
    @idea.user = current_user
    if @idea.save
      redirect_to(ideas_path)
    else
      render "new"
    end
  end

  def edit; end

  def update
    if @idea.update(idea_resource_params)
      redirect_to account_ideas_path
    else
      render "edit"
    end
  end

  def destroy
    @idea.destroy!
    redirect_to account_ideas_path
  end

  private

  def idea_params
    params.permit(:title, :description, :photo_url)
  end

  def idea_resource_params
    params.require(:idea).permit(:title, :photo_url, :done_count, :description)
  end

  def authorize_to_edit_idea
    redirect_to account_path unless can_edit? @idea
  end

  def load_idea
    @idea = Idea.find(params[:id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  include RolesHelper
  before_action :ensure_authenticated
  before_action :load_idea
  before_action :authorize

  def index
    @query = params[:query]
    @query ||= @idea.title
    @photos = Unsplash::Photo.random(query: @query, count: 3)
  end

  def create
    @idea.update_attributes photo_url: params[:photo_url]
    redirect_to edit_idea_path(@idea)
  end

  private

  def load_idea
    @idea = Idea.find(params[:idea_id])
  end

  def authorize
    redirect_to account_path unless can_edit? @idea
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  def atoms
  end

  def molecules
  end

  def organisms
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_admin, only: %i[edit update]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to ideas_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update(edit_user_params)
      redirect_to account_path
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def edit_user_params
    params.require(:user).permit(:email, :name, :role)
  end

  def ensure_admin
    redirect_to account_path unless current_user.role == 'admin'
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
  def has_goal?(goal)
    return false unless logged_in?

    # this resulted in n+1 problem
    # current_user.goals.include? goal
    #
    # this did not correct the n+1 problem, still created lots of requests
    # @goals ||= current_user.goals
    # @goals.include? goal
    #
    # this didn't work, resulted in undefinded method: includes
    # @user ||= User.find(session[:user_id]).includes(:goals)

    @goal_user ||= User.select(:id, :role).includes(:goals).select(:id).find(session[:user_id])
    @goal_user.goals.include? goal
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/roles_helper.rb
module RolesHelper
  def can_edit?(idea)
    case current_user.role
    when 'admin' then true
    when 'registered' then current_user == idea.user
    else false
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_add_goal_btn.html.erb
<%= form_tag(user_goals_path(current_user), id: "goal-#{goal.id}", remote: true) do %>
  <%= hidden_field_tag(:idea_id, goal.id)  %>
  <%= button_tag(type: "submit", class: 'btn delta') do %>
    <svg class="icon-heart icon--sm" role="presentation">
      <use xlink:href="<%= asset_path("icons-defs.svg#heart")%>"></use>
    </svg>
      Add Goal
  <% end %>
<% end %>

app/views/application/_anonymous-header.html.erb
<nav class="site-header__nav">
  <ul class="main-navigation">
    <li><a href="#nolink">Inspiration</a></li>
    <li><a href="#nolink">Sign up</a></li>
    <li><a href="#nolink">Log in</a></li>
  </ul>
</nav>

app/views/application/_anonymous_user_header.html.erb
<nav class="site-header__nav">
  <ul class="main-navigation">
    <li><%= link_to t('inspiration'), ideas_path  %></li>
    <li><%= link_to t('sign_up'), new_user_path  %></li>
    <li><%= link_to t('login'), new_session_path  %></li>
  </ul>
</nav>

app/views/application/_authenticated_user_header.html.erb
<nav class="site-header__nav">
  <ul class="main-navigation">
    <li><%= link_to t('inspiration'), ideas_path  %></li>
    <li><%= link_to t('account'), account_ideas_path  %></li>
    <li><%= button_to(t('logout'), session_path(id: session[:user_id]), method: :delete ) %></li>
  </ul>
</nav>

app/views/application/_editable_idea_card.html.erb
<div id="idea-<%= idea.id  %>"class="card">
  <div class="card__thumb">
    <%= link_to(idea_path(idea)) do  %>
      <% if idea.photo_url.present?  %>
        <img src="<%= idea.photo_url  %>" alt="Northern lights over mountain covered in snow">
      <% else  %>
        <img src="http://fpoimg.com/255x170?text=Preview" alt="Northern lights over mountain covered in snow">
      <% end %>
      <div class="card__intro">
        <h4 class="card__title"><%= idea.title  %></h4>
        <span>75 have done this</span>
      </div>
    <% end %>

  </div>
  <div class="card__footer">
    <%= link_to(idea_path(idea), class: 'btn delta', method: :delete, remote: true) do  %>
      <svg class="icon-delete" role="presentation">
        <use xlink:href="<%= asset_url("icons-defs.svg" + "#delete") %>"></use>
      </svg>
      Delete
    <% end %>

    <%= link_to(edit_idea_path(idea), class: "btn delta", role: "presentation") do %>
      <svg class="icon-edit" role="presentation">
        <use xlink:href="<%= asset_url("icons-defs.svg" + "#edit") %>"></use>
      </svg>
      Edit
    <% end %>
  </div>
</div>

app/views/application/_idea_card.html.erb
<!-- title count img_url  -->
<div class="card">
  <div class="card__thumb">
    <%= link_to idea do  %>
      <img src="<%= idea.photo_url  %>"
           alt="Northern lights over mountain covered in snow">
           <div class="card__intro">
             <h4 class="card__title"><%= idea.title  %>  </h4>
             <span><%= idea.done_count  %> have done this</span>
           </div>
      </img>
    <% end %>
  </div>
  <div class="card__footer">
    <button class="card__btn card__like delta" data-like="see-the-northern-lights">
      <svg class="icon-heart icon-heart--liked" role="presentation">
        <use xlink:href="<%= asset_url("icons-defs.svg" + "#heart") %>"></use>
      </svg>
      Like
    </button>
    <% if logged_in?  %>
      <% if has_goal?(idea)  %>
        <%= render(partial: "remove_goal_btn", locals: {goal: idea})  %>
      <% else  %>
        <%= render(partial: "add_goal_btn", locals: {goal: idea}  )%>
      <% end %>
    <% end %>
  </div>
</div>

app/views/application/_idea_card_editable.html.erb
<div class="card" id="idea-<%= idea.id %>">
  <div class="card__thumb">
    <%= link_to(idea_path(idea)) do %>
       <%= render(partial: "idea_photo", locals: {photo_url: photo_url})  %>
      <div class="card__intro">
        <h4 class="card__title"><%= title    %></h4>
        <span><%= done_count %> have done this.</span>
      </div>
    <% end %>
  </div>
  <div class="card__footer">
    <%= link_to(idea_path(idea), class: 'btn delta', method: :delete, remote: true) do %>
      <svg class="icon-delete" role="presentation">
        <%# <use xlink:href="../icons/icons-defs.svg#delete"></use> %>
        <use href="<%= image_path('icons/icons-defs.svg') %>#delete"></use>
      </svg>
      Delete
    <% end %>
    <a class="btn delta" href="<%= edit_idea_path(idea) %>">
      <svg class="icon-edit" role="presentation">
        <use xlink:href="../icons/icons-defs.svg#edit"></use>
      </svg>
      Edit
    </a>
  </div>
</div>

app/views/application/_idea_photo.html.erb
<% if(photo_url.nil? || photo_url == "") %>
  <img src="http://fpoimg.com/255x170" alt="Northern lights over mountain covered in snow">
  <% else %>
    <%= image_tag(photo_url) %>
  <% end %>

app/views/application/_logged_in_header.html.erb
<nav class="site-header__nav">
  <ul class="main-navigation">
    <li><a href="#nolink">Inspiration</a></li>
    <li><a href="#nolink">Sign up</a></li>
    <li><a href="#nolink">Log in</a></li>
  </ul>
</nav>

app/views/application/_remove_goal_btn.html.erb
<%= link_to(user_goal_path(current_user, goal), method: :delete, id: "goal-#{goal.id}", class: "btn delta" ,remote: true) do %>
    <svg class="icon-delete icon--sm" role="presentation">
      <use xlink:href="<%= asset_path("icons-defs.svg#delete")%>"></use>
    </svg>
    REMOVE GOAL
<% end %>

app/views/application/_search_form.html.erb
<%= form_tag(ideas_path, method: :get, class: 'form full')  do %>
  <div class="input-inline">
    <%= label_tag("global-search-input", "Looking for inspiration?", class: "input-group__label sr-only")  %>
    <div class="input-row">
      <%= text_field_tag( "q", "", id:  "global-search-input", placeholder: t('search.placeholder'), class: "input-row__field") %>
      <%= button_tag(t('search.button'), class: "btn btn--inline btn--primary" )  %>
    </div>
  </div>
<% end %>

app/views/application/_sub_navigation.html.erb
<nav>
  <ul class="sub-navigation">
    <% links = [account_path, account_goals_path, account_ideas_path, root_path] %>
    <% link_names = ['Account', 'Goals', 'Ideas', 'Following'] %>
    <% links.zip link_names %>
    <% links.zip(link_names).each do |link, name| %> 
      <% active = '' %>
      <% active = 'current' if current_page?(link)%>
      <li> <%= link_to(name, link, class: active) %> </li>
    <% end %>
  </ul>
</nav>